POST http://localhost:8080/events
Content-type: application/json

{"name": "Team Meeting",
  "title": "Team Meeting",
  "description": "Discuss project updates",
  "location": "Conference Room",
  "dateTime": "2024-07-01T10:00:00Z",
  "userId": 3
}
