POST http://localhost:8080/events
Content-type: application/json

{"id":3,
  "name": "Google Meet",
  "title": "Google Meet Project Discussion",
  "description": "Discuss project goals and deliverables",
  "location": "Conference Room",
  "dateTime": "2024-07-01T10:00:00Z",
  "userId": 2
}
